version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql/schemas/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "35432:5432"

  password_manager_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: password_manager_service
    container_name: password_manager
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DB_CONNECTION: ${POSTGRES_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      CRYPTO_AES_256_BASE64_KEY: ${CRYPTO_AES_256_BASE64_KEY}
    ports:
      - "8080:8080"

volumes:
  postgres_data:
