components_manager:
    task_processors:                  # Task processor is an executor for coroutine tasks

        main-task-processor:          # Make a task processor for CPU-bound couroutine tasks.
            worker_threads: $worker-threads         # Process tasks in 4 threads.

        fs-task-processor:            # Make a separate task processor for filesystem bound tasks.
            worker_threads: $worker-fs-threads

        monitor-task-processor:       # Make a separate task processor for administrative tasks.
            worker_threads: 2
            thread_name: mon-worker

    default_task_processor: main-task-processor

    components:                       # Configuring components that were registered via component_list
        server:
            listener:                 # configuring the main listening socket...
                port: $server-port            # ...to listen on this port and...
                task_processor: main-task-processor    # ...process incoming requests on this task processor.
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard  # Drop logs if the system is too busy to write them down.

        # Dynamic config options. Cache is disabled, updates are disabled.
        dynamic-config:
            # For most of userver dynamic configs, defaults are used, some are overridden here.
            # See userver "dynamic config" docs for what configs exist.
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000
                POSTGRES_DEFAULT_COMMAND_CONTROL:
                    network_timeout_ms: 750
                    statement_timeout_ms: 500

        testsuite-support: {}

        http-client:
            load-enabled: $is-testing
            fs-task-processor: fs-task-processor

        tests-control:
            load-enabled: $is-testing
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor
        
        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-server-monitor:
            path: /service/monitor
            method: GET
            task_processor: monitor-task-processor
            monitor-handler: false    

        handler-post-user:
            path: /api/v1/user
            method: POST
            task_processor: main-task-processor

        handler-delete-user:
            path: /api/v1/user
            method: DELETE
            task_processor: main-task-processor

        handler-post-auth:
            path: /api/v1/auth
            method: POST
            task_processor: main-task-processor

        handler-get-password:
            path: /api/v1/password/{id}
            method: GET
            task_processor: main-task-processor
            auth:
                types:
                    - bearer

        handler-get-passwords:
            path: /api/v1/passwords
            method: GET
            task_processor: main-task-processor
            auth:
                types:
                    - bearer

        handler-post-password:
            path: /api/v1/password
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                    - bearer

        handler-delete-password:
            path: /api/v1/password/{id}
            method: DELETE
            task_processor: main-task-processor
            auth:
                types:
                    - bearer

        postgres-db-1:
            dbconnection: $dbconnection
            dbconnection#env: DB_CONNECTION
            blocking_task_processor: fs-task-processor
            dns_resolver: async
            sync-start: true
            connlimit_mode: manual

        dns-client:
            fs-task-processor: fs-task-processor

        component-jwt:
            secret_key: $jwt_secret_key
            secret_key#env: JWT_SECRET_KEY
            token_ttl: $jwt_token_ttl
            token_ttl#env: JWT_TOKEN_TTL

        component-crypto:
            aes256_base64_key: $crypto_aes256_base64_key,
            aes256_base64_key#env: CRYPTO_AES_256_BASE64_KEY
